name: Deploy to staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    env:
      API_BASE_URL: ${{ secrets.QA_API_URL }}
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Create env file
        run: echo "API_BASE_URL=$API_BASE_URL" > packages/frontend/.env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.QA_AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build --w packages/frontend

      - name: Bootstrap CDK
        run: npx cdk bootstrap  aws://${{ secrets.QA_AWS_ACCOUNT_ID}}/${{ secrets.AWS_REGION}}

      - name: Deploy stack
        run: cd packages/backend && CORS_ORIGINS=${{ env.STAGE_CORS_ORIGINS }} DOMAIN_NAME=${{ env.STAGE_DOMAIN_NAME }} npx cdk deploy --require-approval never
