name: Deploy to staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.QA_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.QA_AWS_ACCESS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm install
      - name: Bootstrap CDK
        run: npx cdk bootstrap  aws://${{ secrets.QA_AWS_ACCOUNT_ID}}/${{ secrets.AWS_REGION}}
      - name: Synth stack
        run: npx cdk synth
      - name: Deploy stack
        run: npx cdk deploy --require-approval never
