name: Run E2E Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  cypress-run:
    env:
      API_BASE_URL: ${{ secrets.QA_API_URL }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create env file
        run: echo "API_BASE_URL=$API_BASE_URL" > packages/frontend/.env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev --w packages/frontend
          project: ./packages/frontend
          browser: chrome

      - name: Delete env file
        run: rm packages/frontend/.env
